name: Deploy Apps Script

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate Clasp
        run: echo "${{ secrets.CLASP_JSON }}" > ~/.clasprc.json

      - name: Push to Apps Script
        run: |
          clasp push -f
