name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the required Node.js version

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate with Google Service Account
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_CREDENTIALS" > $HOME/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/service-account.json"
          gcloud auth activate-service-account --key-file="$HOME/service-account.json"

      - name: Push changes to Apps Script
        run: clasp push
